name: 'Label Assigner'
description: 'Assigns labels to issues based on the content of the issue'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
