name: ESLint and Prettier Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  lint_and_format:
    name: Check Lint and Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run ESLint and Prettier for Code Formatting
      run: npm run lint-and-format
      # This command must exit with a non-zero status if there are errors that cannot be auto-fixed

    - name: Check for Modified Files
      id: git-check
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "::set-output name=changes_detected::true"
        fi

    - name: Commit and Push Changes if needed
      if: steps.git-check.outputs.changes_detected == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Apply ESLint and Prettier fixes generated by GitHub Actions"
        git push

    - name: Log Results
      run: echo "Linting and formatting checks have been completed successfully."