name: Dynamic Label Assignment

on:
  issues:
    types: [opened, edited]
jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Assign labels based on issue content
      uses: ./.github/actions/label-assign-action
