name: Update Issue Title

on:
  issues:
    types: [opened, edited]

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Issue Title
        uses: ./.github/actions/update-issue-title
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
